services:
  - type: web
    name: voicevox
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    startCommand: ./run.sh
    healthCheckPath: /speakers
    envVars:
      - key: VOICEVOX_ENGINE_TARGET
        value: linux-x64-cpu
      - key: VOICEVOX_ENGINE_VERSION
        value: 0.24.0
      - key: VOICEVOX_ENGINE_REPOSITORY
        value: VOICEVOX/voicevox_engine
