services:
  - type: web
    name: voicevox
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: VV_CPU_NUM_THREADS
        value: "2"
    healthCheckPath: /speakers
    startCommand: ./run.sh
